name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--node20'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.6.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.403'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # Run unit tests
      - name: Run unit tests
        run: dotnet test --no-build --verbosity normal
